apiVersion: v1
kind: Pod
spec:
  containers:
    - name: ansible
      image: docker.io/vmartinvegatraining/bootcamp-ansible:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: IfNotPresent
